name: Changelog Bot on Telegram

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run the bot
        run: python bot.py  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  
          CHAT_ID: ${{ secrets.CHAT_ID }}  
